#define DRIVETRAIN_ENABLED
#define VISION_ENABLED

#define PIVOT_ENABLED
#define ELEVATOR_ENABLED
#define INTAKE_ENABLED
#define FUNNEL_ENABLED
#define DYNAMIC_PIVOT_ENABLED

#define OPERATOR_CONTROLLER
#define OPERATOR_BUTTON_BOX